# Generated by Django 2.2.2 on 2019-06-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsystem',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
